---
title: "TreeAndLeaf: a package for reorganizing dendrograms in order to represent multiple layers of information"
author: "Leonardo W Kume"
date: "`r BiocStyle::doc_date()`"
output: 
  BiocStyle::html_document:
    css: custom.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Case Studies

## USA Arrests

This is a simple example to show the versatility of the package.

1 - Clusterize the data from the USA Arrests dataset.

```{r, eval=FALSE}
hc <- hclust(dist(USArrests), "ave")
```

2 - Convert the hclust to an igraph object.

```{r, eval=FALSE}
gg <- hclust2igraph(hc)
```


3 - Set the nodes names.

```{r, eval=FALSE}
idx <- which(V(gg$g)$name %in% hc$labels)
V(gg$g)$nodeAlias <- V(gg$g)$name
```

4 - Create the color pallete based on the murder rate for each state.

```{r, eval=FALSE}
murder <- USArrests$Murder
qnts <- quantile(murder, seq(0, 1, 0.2))
pal <- brewer.pal(5, "Reds")
col <- rep(NA, length(murder))
col[murder < qnts[2]] <- pal[1]
col[murder >= qnts[2] & murder < qnts[3]] <- pal[2]
col[murder >= qnts[3] & murder < qnts[4]] <- pal[3]
col[murder >= qnts[4] & murder < qnts[5]] <- pal[4]
col[murder >= qnts[5] & murder <= qnts[6]] <- pal[5]
names(col) <- rownames(USArrests)
```


